export const AUTH_START = "AUTH_START";
export const AUTH_END = "AUTH_END";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const CLEAN_UP = "CLEAN_UP";

export const VERIFY_START = "VERIFY_START";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const RECOVERY_START = "RECOVERY_START";
export const RECOVERY_SUCCESS = "RECOVERY_SUCCESS";
export const RECOVERY_FAIL = "RECOVERY_FAIL";

export const PROFILE_EDIT_START = "PROFILE_EDIT_START";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAIL = "PROFILE_EDIT_FAIL";

export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const DELETE_START = "DELETE_START";
export const DELETE_FAIL = "DELETE_FAIL";

export const ADD_GNOME_START = "ADD_GNOME_START";
export const ADD_GNOME_SUCCESS = "ADD_GNOME_SUCCESS";
export const ADD_GNOME_FAIL = "ADD_GNOME_FAIL";

export const DELETE_GNOME_START = "DELETE_GNOME_START";
export const DELETE_GNOME_SUCCESS = "DELETE_GNOME_SUCCESS";
export const DELETE_GNOME_FAIL = "DELETE_GNOME_FAIL";

export const EDIT_GNOME_HOSE_START = "EDIT_GNOME_HOSE_START";
export const EDIT_GNOME_HOSE_SUCCESS = "EDIT_GNOME_HOSE_SUCCESS";
export const EDIT_GNOME_HOSE_FAIL = "EDIT_GNOME_HOSE_FAIL"